# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 160, 47, 13))
        self.label.setObjectName("label")
        self.PlainText_plt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PlainText_plt.setGeometry(QtCore.QRect(160, 130, 601, 71))
        self.PlainText_plt.setObjectName("PlainText_plt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 47, 13))
        self.label_2.setObjectName("label_2")
        self.CipherText_plt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.CipherText_plt.setGeometry(QtCore.QRect(160, 290, 601, 71))
        self.CipherText_plt.setObjectName("CipherText_plt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 50, 101, 16))
        self.label_4.setObjectName("label_4")
        self.Encrypt_pb = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt_pb.setGeometry(QtCore.QRect(200, 420, 75, 23))
        self.Encrypt_pb.setObjectName("Encrypt_pb")
        self.Decrypt_pb = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt_pb.setGeometry(QtCore.QRect(640, 420, 75, 23))
        self.Decrypt_pb.setObjectName("Decrypt_pb")
        self.Key_plt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Key_plt.setGeometry(QtCore.QRect(160, 230, 601, 31))
        self.Key_plt.setObjectName("Key_plt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Plain Text:"))
        self.label_2.setText(_translate("MainWindow", "Key:"))
        self.label_3.setText(_translate("MainWindow", "CipherText:"))
        self.label_4.setText(_translate("MainWindow", "RAILFENCE CIPHER"))
        self.Encrypt_pb.setText(_translate("MainWindow", "Encrypt"))
        self.Decrypt_pb.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
